version: '3.8'

services:
  app:
    volumes:
      # Override to mount src but preserve models from the image
      - ./src/api:/app/src/api
      - ./src/agent:/app/src/agent  
      - ./src/capture:/app/src/capture
      - ./src/control:/app/src/control
      - ./src/runner:/app/src/runner
      - ./src/utils:/app/src/utils
      - ./src/config.py:/app/src/config.py
      - ./src/main.py:/app/src/main.py
      - ./src/__init__.py:/app/src/__init__.py
      # Models directory comes from the Docker image, not mounted
      - ./tests:/app/tests
      - ./screenshots:/app/screenshots
      - ./datasets:/app/datasets
      - ./training:/app/training
      - ./testing:/app/testing
      - ./reports:/app/reports
      - ./logs:/app/logs
      - ./.env:/app/.env

  runner:
    volumes:
      # Same approach for runner service
      - ./src/api:/app/src/api
      - ./src/agent:/app/src/agent
      - ./src/capture:/app/src/capture
      - ./src/control:/app/src/control
      - ./src/runner:/app/src/runner
      - ./src/utils:/app/src/utils
      - ./src/config.py:/app/src/config.py
      - ./src/main.py:/app/src/main.py
      - ./src/__init__.py:/app/src/__init__.py
      # Models directory comes from the Docker image, not mounted
      - ./tests:/app/tests
      - ./reports:/app/reports
      - ./screenshots:/app/screenshots
      - ./datasets:/app/datasets
      - ./training:/app/training
      - ./testing:/app/testing
      - ./.env:/app/.env